# Generated by Django 4.2.11 on 2024-04-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_app', '0003_category_user_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytype',
            old_name='category_name',
            new_name='name',
        ),
    ]
